language: node_js
node_js: 'node'
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/
cache: yarn
script:
  - yarn test
  - yarn coveralls
  - yarn lint
  - yarn build-storybook
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    local-dir: dist
